export interface Project {
  slug: string;
  title: string;
  location: string;
  vertical: "Retail" | "Commercial" | "Hospitality";
  summary: string;
  scope: string;
  challenge: string;
  solution: string;
  outcome: string;
  images: string[];
  video?: string; // YouTube/Vimeo embed URL
}


export const PROJECTS: Project[] = [
  {
    slug: "stylerunner",
    title: "Stylerunner",
    location: "Kotara, NSW",
    vertical: "Retail",
    summary: "A 105m² premium retail fitout for the Accent Group, delivered defect-free and on time.",
    scope: "105m² premium retail fitout for the Accent Group.",
    challenge: "Creating a high-interaction space where technical lighting and custom joinery make product ranges shine to drive revenue.",
    solution: "We leveraged our long-term partnership with Accent Group to execute a precision build focused on seamless fashion-functionality integration.",
    outcome: "A 100% defect-free handover by the due date — positioning Hallmarc to complete multiple ongoing projects with the parent group.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/e537c253f123a94b?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/154c74be5631fd80?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/033547e5d10779a3?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/500b15c251fce961?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/ebb0f0ac06484df0?_a=BAMAPqa80",
    ],
  },
  {
    slug: "nudie-jeans",
    title: "Nudie Jeans",
    location: "James St, Brisbane",
    vertical: "Retail",
    summary: "A 40m² hyper-sustainable specialty store — featured in INDESIGNLIVE and longlisted for the 2024 Dezeen Awards.",
    scope: "40m² specialty retail store focused on hyper-sustainability.",
    challenge: "Meeting a complex brief aligned with the brand's commitment to lifetime garment repair and environmental responsibility.",
    solution: "We sourced and installed specialty sustainable materials through clear communication and artisanal problem-solving.",
    outcome: "Global-stage results — the fitout was featured in INDESIGNLIVE and longlisted for the 2024 Dezeen Awards for sustainable interiors.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/d4c2fd5891d4b344?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/19082e7c528329ea?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/c369544cce113e5b?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/62e6c9cb11060b78?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/fe380c380992bc7c?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/b392013737fa491d?_a=BAMAPqa80",
    ],
  },
  {
    slug: "dissh",
    title: "DISSH Boutiques",
    location: "Head Office, Level 28, George St, Brisbane",
    vertical: "Commercial",
    summary: "A 1,000m² head office fitout for DISSH in Brisbane — delivered two weeks early and under budget.",
    scope: "Project management, on-site supervision, off-site manufacture.",
    challenge: "DISSH is a female-founded Australian fashion brand. They needed their 1,000m² new-build head office in Brisbane to reflect the brand's essence: sustainably minded, thoughtfully designed, and laidback in style.",
    solution: "Working to the architectural design and specifications, the Hallmarc team seamlessly pivoted to accommodate design changes — re-quoting swiftly and securing council approvals while maintaining the schedule. We delivered two weeks early and under budget.",
    outcome: "An immersive space brimming with light, texture and elegance — a space that makes employees want to stay, and where they feel inspired to do their best work.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/1e8ec59a873c1cca?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/6b05b6b63b862977?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/c54995372d687649?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/1de418fe825ff33f?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/7543573cc83967c6?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/04630281ba6c3787?_a=BAMAPqa80",
    ],
  },
  {
    slug: "eveleigh",
    title: "the Eveleigh",
    location: "Display Suite, Broadbeach",
    vertical: "Commercial",
    summary: "A complex commercial display suite delivered within a fixed 4.5-week program.",
    scope: "Project management, trade coordination, program management, delivery.",
    challenge: "Deliver a complex commercial display environment within a fixed 4.5-week program, coordinating all trades and maintaining design integrity.",
    solution: "Our senior-led team managed trades, program constraints and the client's design vision within a fixed timeframe.",
    outcome: "Display suite delivered on time, on budget, and to the standard the developer required to launch to market.",
    images: ["https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/fed0c4519d6fa0fa?_a=BAMAPqa80"],
  },
  {
    slug: "zambrero",
    title: "Zambrero",
    location: "Nicholas Street Precinct, Ipswich",
    vertical: "Hospitality",
    summary: "An ongoing national QSR rollout, delivered with consistent quality across diverse locations.",
    scope: "Continuous partnership supporting a significant national store rollout across QSR chain Zambrero.",
    challenge: "Maintaining extreme quality consistency and craftsmanship while scaling rapidly across diverse national locations.",
    solution: "Since installing our first Zambrero site in 2021, our senior team has provided a level of calmness and concise communication to navigate the high-pressure rollout schedule.",
    outcome: "Hallmarc is recognised as a standout in the pack for attention to detail and top-tier finishes that drive brand growth.",
    images: [
      "/images/zambrero-drivethrough.jpg",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/3f66daeffd0771c4?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/6b0ed27703ae984a?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/c7cb6d41cd74785c?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/4ede8e81e3ee20f3?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/ecfe7fb749d4049f?_a=BAMAPqa80",
    ],
  },
  {
    slug: "justgroup",
    title: "the Just Group",
    location: "National Rollout",
    vertical: "Retail",
    summary: "15 years and 1,000+ locations across seven fashion brands — Peter Alexander, Just Jeans, Jay Jays, Jacqui E, Portmans, Dotti and Smiggle.",
    scope: "Collaboration across 7 fashion brands and 1,000+ locations over 15 years — Peter Alexander, Just Jeans, Jay Jays, Jacqui E, Portmans, Dotti and Smiggle.",
    challenge: "Providing a personalised, boutique-level service for over a decade to one of Australia's largest retail groups.",
    solution: "Consistently demonstrating a commitment to personalised service and the ability to jump through fiery hoops for the curly projects.",
    outcome: "A long-term partnership where Hallmarc remains a foremost choice for shopfitting, thanks to cost-effective and top-notch outcomes.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/e5f9d6cf1fb4850c?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/3d4c08b379116657?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/f16cb4a88651ccda?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/b9e9d24fc223d100?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/e80df2826541196f?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/39d9d7a354a24330?_a=BAMAPqa80",
    ],
  },
  {
    slug: "city-beach",
    title: "City Beach",
    location: "Ballina Fair, NSW",
    vertical: "Retail",
    summary: "A 400m² fitout for the iconic Australian surf retailer, delivered on time through mid-stream design changes.",
    scope: "400m² retail fitout for an iconic Australian surf retailer.",
    challenge: "Handling significant client-side changes to both the design and off-site manufacturing requirements mid-stream.",
    solution: "We managed the entire project coordination burden, overseeing production adjustments to shield the client from the complexity.",
    outcome: "Delivered on time to an impressed client — a store that captures Australia's youth culture through high-impact design and a community-focused space.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/04ef9107c9d862f7?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/05c456282e0d5c8d?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/8b549ec1e7baed41?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/f7da275ea756606e?_a=BAMAPqa80",
    ],
  },
  {
    slug: "terminus",
    title: "Terminus Hotel",
    location: "Yarrawonga, Victoria",
    vertical: "Hospitality",
    summary: "A historic hotel restoration — structural works, concrete cutting and bespoke joinery within a heritage framework.",
    scope: "Comprehensive project management across structural restoration and custom architectural elements for the historic Terminus Hotel.",
    challenge: "Delivering major structural works — including restumping and new structural supports — while integrating precise concrete cutting, feature archways and detailed joinery within an existing heritage framework.",
    solution: "Hallmarc oversaw the majority of the build, coordinating structural reinforcement and managing complex concrete modifications. Custom internal cabinetry was delivered alongside bespoke timber-finished windows and doors, crafted to align with the hotel's architectural character.",
    outcome: "A structurally revitalised, design-led hospitality space that balances durability with craftsmanship — reflecting both its historic foundations and a refined contemporary finish.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/5597c2fc0eb1eb54?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/93667ef4df4c4eea?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/f4117f13a1869756?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/011069b75bdbeca4?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/279e12c9811b0192?_a=BAMAPqa80",
    ],
  },
  {
    slug: "honeybirdette",
    title: "Honey Birdette",
    location: "Rundle Mall, Adelaide",
    vertical: "Retail",
    summary: "A 63m² boudoir-inspired boutique with bespoke joinery and crafted mood lighting.",
    scope: "Honey Birdette's boutique on Rundle Mall in Adelaide called for a fitout that matched the brand's playful, sensual identity — highly detailed fixtures, finishes and fittings designed to create an immersive retail experience. Custom joinery and crafted mood lighting were essential to display luxury lingerie and accessories in a way that encouraged customers to stay and explore.",
    challenge: "The design intent was bold and atmospheric, drawing inspiration from the boudoir. Achieving it meant integrating lush decor, refined lighting and tailored display elements within a compact 63m² footprint — balancing high-end detailing with practical retail functionality without compromising durability or flow.",
    solution: "Hallmarc approached the fitout with meticulous attention to staging and coordination. We delivered custom joinery aligned with the delicate, sculptural design language, integrating crafted mood lighting to enhance product displays and ambiance, and coordinating trades for seamless transitions between installation stages.",
    outcome: "An unapologetically sensual and engaging retail environment that reflects the Honey Birdette brand — thoughtfully crafted detailing, dynamic lighting and bespoke joinery that invite customers to linger longer and explore with confidence.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/da74d6794f5cd16a?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/ea0fd198254de15b?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/6dd2db7645da0bea?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/c5bb472d7267e2d9?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/91fb044797b9d5a6?_a=BAMAPqa80",
    ],
  },
  {
    slug: "lovisa",
    title: "Lovisa",
    location: "Runaway Bay, Queensland",
    vertical: "Retail",
    summary: "A jewellery store fitout delivered ahead of schedule — setting the precedent for future rollouts.",
    scope: "The Lovisa store in Runaway Bay presented a unique retail challenge: how to make a space housing thousands of small, shiny fashion accessories feel inviting, confident and easy to explore. Hallmarc delivered the fitout — lighting, joinery and finishes — to elevate the shopping experience in a way that reflected the global jewellery brand's stylish identity.",
    challenge: "Jewellery and accessory retailers demand environments that balance visual intrigue with clarity and flow. The challenge for Lovisa was to showcase product abundance without sacrificing spatial comfort or brand presence — all while meeting timelines and setting the stage for future stores.",
    solution: "Hallmarc combined lighting strategy, custom joinery and high-quality finishes to shape a space that felt both social and confident. Careful coordination between service trades and design intent guided sightlines, enhanced product visibility and delivered consistency in materiality and brand language. The project was delivered ahead of schedule.",
    outcome: "An inviting retail environment that elevates the customer experience while clearly expressing the brand's identity. The integration of lighting and joinery showcased thousands of products without overwhelming the space — leading to further rollouts for the brand.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/94b3751a41ff6543?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/06b9a43bfafbe07b?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/5b7c5033df5e6090?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/5a38a5b416290586?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/c58e6f9b559ae851?_a=BAMAPqa80",
    ],
  },
  {
    slug: "industrie",
    title: "Industrie",
    location: "Moggill Rd, Indooroopilly QLD",
    vertical: "Retail",
    summary: "A contemporary fashion fitout delivered with minimal disruption inside a live retail centre.",
    scope: "Industrie enlisted Hallmarc to deliver a fitout aligned with the fashion brand's modern aesthetic and customer-experience goals — custom joinery, interior installations, lighting and finishes designed to reflect the label's contemporary identity and optimise retail flow.",
    challenge: "Industrie's retail environment demanded a balance between bold visual appeal and functional clarity. With high product turnover and a focus on fashion presentation, the space needed to feel inviting and easy to navigate while expressing the brand's distinct design language — all delivered within a live retail centre.",
    solution: "Hallmarc coordinated joinery, lighting and interior trades to deliver a cohesive result. Custom joinery was manufactured to enhance product display and circulation, while finishes and lighting elevated brand perception. The project was staged to align with the broader centre's logistics, ensuring minimal disruption and programmed handovers.",
    outcome: "A confident, well-resolved environment that reflects the brand's contemporary fashion focus. Thoughtful detailing and coordinated lighting enhance product visibility and customer engagement — a visually compelling, fully functional store that supports both brand identity and operational flow.",
    images: [
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/766bae296430595d?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/efeed8b1d8945fd0?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/caa077a1a508c7a2?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/af3b0610ca837dac?_a=BAMAPqa80",
      "https://res.cloudinary.com/dp77cjpmn/image/upload/f_auto,q_auto/v1/hallmarc/projects/a3fbe14d1e4cde22?_a=BAMAPqa80",
    ],
  },
];

export function getProject(slug: string) {
  return PROJECTS.find((p) => p.slug === slug);
}
